/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcarereportsystem;

import static healthcarereportsystem.HealthCareReportSystem.goKlickedPage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;

/**
 *
 * @author pc
 */
public class DoctorProfile extends javax.swing.JFrame {

    /**
     * Creates new form DoctorProfile
     */
    //private static int userId;
    public DoctorProfile() {
        initComponents();
      
         //JOptionPane.showMessageDialog(null, "Doctor Id = "+ userid+", username = "+username + ", Profilename = "+profileName);
        //doctorNameShow.setText(profileName);
    }

    public JLabel getUserid() {
        return did;
    }


    public static JLabel getDoctorNameShow() {
        return dn;
    }
    


    public static void setDoctorNameShow(JLabel doctorNameShow) {
        DoctorProfile.dn = doctorNameShow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dn = new javax.swing.JLabel();
        sendTest = new javax.swing.JButton();
        sendPrescription = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        did = new javax.swing.JLabel();
        bmdc = new javax.swing.JLabel();
        sp = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        dg = new javax.swing.JLabel();
        clg = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        sx = new javax.swing.JLabel();
        em = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dn.setText("Doctor Name");

        sendTest.setText("Send Test");
        sendTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendTestActionPerformed(evt);
            }
        });

        sendPrescription.setText("Send Prescription");
        sendPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPrescriptionActionPerformed(evt);
            }
        });

        jButton4.setText("Back");

        home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        did.setText("Doctor id");

        bmdc.setText("bmdc");

        sp.setText("speciality");

        ps.setText("posting");

        dg.setText("degree");

        clg.setText("college");

        pn.setText("phone");

        bg.setText("bloodgroup");

        db.setText("date of birth");

        sx.setText("sex");

        em.setText("email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sendPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmdc)
                    .addComponent(sp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dg)
                        .addComponent(ps)
                        .addComponent(clg)))
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(em)
                    .addComponent(sx)
                    .addComponent(db)
                    .addComponent(bg)
                    .addComponent(pn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dn)
                    .addComponent(pn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(did)
                    .addComponent(bg))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmdc)
                    .addComponent(db))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp)
                    .addComponent(sx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps)
                    .addComponent(em))
                .addGap(18, 18, 18)
                .addComponent(dg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(sendTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendPrescription)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(home))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        StartPage st = new StartPage();
        goKlickedPage(this,st);
    }//GEN-LAST:event_homeActionPerformed

    private void sendTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTestActionPerformed
        // TODO add your handling code here:
          SendTest field = new SendTest();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sendTestActionPerformed

    private void sendPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPrescriptionActionPerformed
        // TODO add your handling code here:
         SendPrescription field = new SendPrescription();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sendPrescriptionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
        
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=HealthCareReportSystem;selectMethod=cursor", "sa", "7896");

                
             String sql = "Select Doctor_.firstName, Doctor_.doctorID, Doctor_.speciality, Doctor_.BDMCNO, Doctor_.speciality, Doctor_.currentWorkingPlace, Doctor_.degree, Doctor_.graduatedFrom, Doctor_.contact, Doctor_.bloodGroup, Doctor_.dateOFBirth, Doctor_.sex, DoctorLogIn_.email from Doctor_ INNER JOIN DoctorLogIn_ ON Doctor_.userName = DoctorLogIn_.userName WHERE Doctor_.userName = ?";
                        
                        PreparedStatement pst = connection.prepareStatement(sql);
                        pst.setString(1, DoctorSignIn.Dusername);
                        
                        ResultSet rs = pst.executeQuery();
                        
                        while(rs.next())
                        {
                            
                            
                            dn.setText(rs.getString("firstName"));
                            em.setText(rs.getString("email"));
                            sp.setText(rs.getString("speciality"));
                            ps.setText(rs.getString("currentWorkingPlace"));
                            dg.setText(rs.getString("degree"));
                            clg.setText(rs.getString("graduatedFrom"));
                            pn.setText(rs.getString("contact"));
                            bg.setText(rs.getString("bloodGroup"));
                            db.setText(rs.getString("dateOFBirth"));
                            sx.setText(rs.getString("sex"));
                            bmdc.setText(rs.getString("BDMCNO"));
                            did.setText(rs.getString("doctorID"));
                            
                            
                            
                            
                        }

            } catch (Exception e) {
                e.printStackTrace();
            }

        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bmdc;
    private javax.swing.JLabel clg;
    private javax.swing.JLabel db;
    private javax.swing.JLabel dg;
    private javax.swing.JLabel did;
    private static javax.swing.JLabel dn;
    private javax.swing.JLabel em;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel pn;
    private javax.swing.JLabel ps;
    private javax.swing.JButton sendPrescription;
    private javax.swing.JButton sendTest;
    private javax.swing.JLabel sp;
    private javax.swing.JLabel sx;
    // End of variables declaration//GEN-END:variables
}
