/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcarereportsystem;

import static healthcarereportsystem.ConnectMSSQL.cn;
import static healthcarereportsystem.HealthCareReportSystem.goKlickedPage;
import static healthcarereportsystem.HealthCareReportSystem.profileName;
import static healthcarereportsystem.HealthCareReportSystem.userid;
import static healthcarereportsystem.HealthCareReportSystem.username;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JLabel;

import static healthcarereportsystem.HealthCareReportSystem.profileName;


/**
 *
 * @author pc
 */
public class DoctorProfile extends javax.swing.JFrame{

    /**
     * Creates new form DoctorProfile
     */
    //private static int userId;
    public DoctorProfile() {
        initComponents();

      
         //JOptionPane.showMessageDialog(null, "Doctor Id = "+ userid+", username = "+username + ", Profilename = "+profileName);
        //doctorNameShow.setText(profileName);
    }

    public JLabel getUserid() {
        return userid_;
    }


    public static JLabel getDoctorNameShow() {
        return doctorNameShow;
    }
    


    public static void setDoctorNameShow(JLabel doctorNameShow) {
        DoctorProfile.doctorNameShow = doctorNameShow;
        doctorNameShow.setText(profileName);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorNameShow = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        sendTest = new javax.swing.JButton();
        sendPrescription = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        userid_ = new javax.swing.JLabel();
        bmdc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doctorNameShow.setText("Doctor Name");

        details.setText("Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        sendTest.setText("Send Test");
        sendTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendTestActionPerformed(evt);
            }
        });

        sendPrescription.setText("Send Prescription");
        sendPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPrescriptionActionPerformed(evt);
            }
        });

        jButton4.setText("Back");

        home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        userid_.setText("Doctor id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendPrescription)
                    .addComponent(sendTest))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorNameShow, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(details))
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userid_, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmdc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorNameShow)
                    .addComponent(userid_))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(details)
                    .addComponent(bmdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(sendTest)
                .addGap(35, 35, 35)
                .addComponent(sendPrescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(home))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        StartPage st = new StartPage();
        goKlickedPage(this,st);
    }//GEN-LAST:event_homeActionPerformed

    private void sendTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTestActionPerformed
        // TODO add your handling code here:
          SendTest field = new SendTest();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sendTestActionPerformed

    private void sendPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPrescriptionActionPerformed
        // TODO add your handling code here:
         SendPrescription field = new SendPrescription();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sendPrescriptionActionPerformed


    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
//        // TODO add your handling code here:





            d_details st = new d_details();
            goKlickedPage(this,st);




















//
//            // TODO add your handling code here:
//        
//        // TODO add your handling code here:
//        try {
//            ConnectMSSQL con = new ConnectMSSQL();
//            con.connectDatabase();
//
////            d_details st = new d_details();
////            goKlickedPage(this,st);
//            
//            String s = userid_.getText();
//      
//
//            String sql = "SELECT * FROM Doctor_ WHERE doctorID = 's'";
//
//
//
//            PreparedStatement pst = cn.prepareCall(sql);
//
//
//            ResultSet rs = pst.executeQuery();
//
//           
//           // getProfileName(rs);
//
//
//          //  DoctorProfile.getDoctorNameShow().setText(profileName);
//          
//          
//            //d_details.getUserid().setText(Integer.toString(userid));
//            
//            String sid = rs.getString("country");
//            bmdc.setText(sid);
//
//
//
//        } catch (ClassNotFoundException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//
//
//
//
//
//






//        
//        // TODO add your handling code here:
//        try {
//            ConnectMSSQL con = new ConnectMSSQL();
//            con.connectDatabase();
//            
//            String s = userid_.getText();
//      
//
//           // String sql = "SELECT * FROM DoctorLogIn_ WHERE userName=? and password=?";
//
//            String sql1 = "select * from Doctor_ where =?"; // profile
//
//            PreparedStatement pst = cn.prepareCall(sql);
//
//            PreparedStatement pstName = cn.prepareCall(sql1); // profile
//
//           // logInDoctorandFetchName(pst, pstName, this);
//
//            ResultSet rs = pst.executeQuery();
//            ResultSet rs1 = pstName.executeQuery();
//           
//            getProfileName(rs1);
//
//            cn.close();
//
//            resetLoginFields(userName, password);
//
//            
//            
//            JOptionPane.showMessageDialog(null, "Doctor Id = "+ userid+", username = "+username + ", Profilename = "+profileName);
//            DoctorProfile.getDoctorNameShow().setText(profileName);
//          
//            DoctorProfile.getUserid().setText(Integer.toString(userid));
//
//            if (b) {
//                HealthCareReportSystem.goKlickedPage(this, DoctorProfile);
//            } else {
//                JOptionPane.showMessageDialog(null, "Invalid pass or user name");
//            }
//
//        } catch (ClassNotFoundException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }

    }//GEN-LAST:event_detailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bmdc;
    private javax.swing.JButton details;
    private static javax.swing.JLabel doctorNameShow;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton sendPrescription;
    private javax.swing.JButton sendTest;
    private javax.swing.JLabel userid_;
    // End of variables declaration//GEN-END:variables
}
