/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcarereportsystem;

import static healthcarereportsystem.ConnectMSSQL.cn;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajal
 */
public class PatientData extends javax.swing.JFrame {

    /**
     * Creates new form PatientData
     */
    public PatientData() {
        initComponents();
        show_data();    /// initialize the method
    }
    
    
    public ArrayList<PatientTable>patinetList(){
        ArrayList<PatientTable>patientList = new ArrayList<>();
        
        try {
            ConnectMSSQL con = new ConnectMSSQL();
            con.connectDatabase(); 
            
            
            
            
            String query1 = "SELECT * FROM Patient_";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            PatientTable pTable;
            
        
            while(rs.next())
            {
                pTable = new PatientTable(rs.getInt("patientId"), rs.getString("userName"), rs.getString("firstName"), rs.getString("lastName"), rs.getString("bloodGroup"), rs.getString("sex"), rs.getString("dateOFBirth"), rs.getString("contact"), rs.getString("country"), rs.getString("division"), rs.getString("district"), rs.getString("village"), rs.getString("thana"), rs.getString("road"), rs.getString("houseNo"));
                
                patientList.add(pTable);
            }
            
        
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        return patientList;
    }
    
    public void show_data(){
        ArrayList<PatientTable> list = patinetList();
        DefaultTableModel model = (DefaultTableModel) jTable_patient.getModel();
        Object[] row  = new Object[15];  /// total column value passing
        
        
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getPid();
            row[1] = list.get(i).getUname();
            row[2] = list.get(i).getFname();
            row[3] = list.get(i).getLname();
            row[4] = list.get(i).getBg();
            row[5] = list.get(i).getSex();
            row[6] = list.get(i).getDob();
            row[7] = list.get(i).getPhone();
            row[8] = list.get(i).getCountry();
            row[9] = list.get(i).getDivision();
            row[10] = list.get(i).getDistrict();
            row[11] = list.get(i).getVillage();
            row[12] = list.get(i).getThana();
            row[13] = list.get(i).getRoad();
            row[14] = list.get(i).getHouse();
            
            model.addRow(row);
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_patient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_patient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "patient ID", "username", "First name", "Last name", "blood", "sex", "DOB", "Phone", "Country", "Division", "District", "Village", "Thana", "Road ", "House"
            }
        ));
        jScrollPane1.setViewportView(jTable_patient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 284, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_patient;
    // End of variables declaration//GEN-END:variables
}
